---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: personal-fedora-sway

description: A personal Atomic Fedora image with Sway WM, NVIDIA/CUDA drivers, development tools, and more.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - negativo17
  - type: dnf
    repos:
      files:
        - https://src.fedoraproject.org/rpms/fedora-repos/raw/f42/f/fedora-cisco-openh264.repo
      copr:
        - atim/starship
       # - lizardbyte/beta # Stable not yet built as of 5/8/25
        - mhartgring/pqiv
        - lihaohong/yazi
        - atim/i3status-rust
        - alternateved/tofi
        - solopasha/hyprland
    install:
      allow-erasing: true
      packages:
        - xorg-x11-server-Xorg
        - xorg-x11-server-Xwayland
        - xorg-x11-nvidia
        - intel-gpu-tools
        - libva-intel-media-driver
        - sway
        - swayidle
        - swaylock
        - xdg-desktop-portal
        #- rofi
        - tofi
        - wl-clipboard
        - cargo
        - wdisplays
        - wlr-randr
        - fprintd-pam
        - i3status-rust
        - nut
        - pipewire-devel
        - qt5-qtwayland
        - qt6-qtwayland
        - trash-cli
        - playerctl
        - uwsm
        - hyprpicker
        - pipewire
        - wireplumber
        - mako # Notification daemon
        - pqiv # Image viewer
        - qimgv # Image gallery viewer
        - mpv # Video player
        #- satty # Screenshot/annotate
        - grimshot # Screenshot
        - foot # Minimal terminal
        #- Sunshine # Low-latency remote desktop
        - gitui

        - yazi # TUI file browser
        - jq
        - poppler
        - fd-find
        - ripgrep
        - fzf
        - zoxide
        - ImageMagick
        - exiftool

        - gnome-keyring

        # ripdrag
        - gdk-pixbuf2-devel
        - pango-devel
        - graphene-devel
        - cairo-gobject-devel
        - cairo-devel
        - python3-cairo-devel
        - gtk4-devel

        - cuda-devel
        - argyllcms

        # LY DEPS
        #- kernel-devel
        #- pam-devel 
        #- libxcb-devel

        #- greetd
        #- tuigreet

        - openrgb

        # Virtualization Tools
        - libvirt # Virtualization library and daemon
        - virt-install # Command line tool for installing VMs

        - starship
        - conda
        - tailscale
        - zsh
        - p7zip

        # Multimedia Codecs and Thumbnail Generators
        - ffmpeg
        - gstreamer1
        - gstreamer1-plugin-libav # FFmpeg plugin for GStreamer
        - libvkd3d
        #- intel-media-driver # RPMFUSION Intel Media Driver for VAAPI (if you have Intel iGPU)

        - openh264 # Cisco OpenH264 codec

        # Packages for working with Apple Devices
        - usbmuxd
        - libimobiledevice-utils
        - ifuse

        - android-tools
        - https://github.com/Martichou/rquickshare/releases/download/v0.11.5/r-quick-share-main_v0.11.5_glibc-2.39_1-x86_64.rpm
        - jmtpfs

        - libxcrypt-compat

        # Extensive Development Extras
        - make
        - gcc
        - glibc-devel
        - git
        - gh
        - cmake
        - clang
        - htop
        - nano
        - helix
        - gdb
        # DisplayCal
        - dbus
        - pkgconf
        - gtk3-devel
        - libXxf86vm-devel
        - python3-devel
        - python3-virtualenv
        - valgrind
        - strace
        - ltrace
        - pkgconf-pkg-config
        - zlib-devel
        - bzip2-devel
        - xz-devel
        - openssl-devel
        - elfutils-libelf-devel
        - libffi-devel
        - readline-devel
        - ncurses-devel
        - dbus-devel
        - usbutils
        - lshw
        - pciutils
        - ddrescue
        - docker
        - podman
        - python3
        - python3-pip

    remove:
      packages:
        #- mesa-libGL
        #- mesa-dri-drivers
        - noopenh264
        - firefox

  - type: files
    files:
    - source: finish-setup.service
      destination: /usr/lib/systemd/system/finish-setup.service
    - source: finish-setup-user.service
      destination: /usr/lib/systemd/user/finish-setup-user.service
    - source: finish-setup.sh
      destination: /usr/etc/finish-setup/finish-setup.sh
    - source: finish-setup-user.sh
      destination: /usr/etc/finish-setup/finish-setup-user.sh
    - source: home
      destination: /usr/etc/finish-setup/home

#  - type: script
#    scripts:
#      - install-ly.sh

  - type: systemd

    system:
      enabled:
        - libvirtd.service
        #- greetd.service
        #- ly.service
        - finish-setup.service
        - tailscaled.service
    user:
      enabled:
        - finish-setup-user.service

  - type: default-flatpaks
    system:
      install:
        - org.mozilla.firefox
        - org.chromium.Chromium

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - SourceCodePro
        - JetBrainsMono
        - CodeNewRoman
        - NerdFontsSymbolsOnly

  - type: signing



#- https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
#- https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
#- https://negativo17.org/repos/fedora-nvidia.repo
#- https://negativo17.org/repos/fedora-multimedia.repo
#- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-42/atim-starship-fedora-42.repo
