---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: personal-fedora-sway

description: A personal Atomic Fedora image with Sway WM, NVIDIA/CUDA drivers, development tools, and more.

base-image: ghcr.io/ublue-os/base-nvidia
image-version: 42

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: bling
    install:
      - negativo17
  - type: dnf
    repos:
      files:
        - https://src.fedoraproject.org/rpms/fedora-repos/raw/f42/f/fedora-cisco-openh264.repo
 #       - https://developer.download.nvidia.com/compute/cuda/repos/fedora41/x86_64/cuda-fedora41.repo
      copr:
        - atim/starship
        - lihaohong/yazi
        - atim/i3status-rust
        - alternateved/tofi
        - solopasha/hyprland # uwsm satty
        - ploxold/sway-stable
#        - gloriouseggroll/nobara-42

    install:
      allow-erasing: true
      packages:
        # --- Core Display & Window Manager ---
        - xorg-x11-server-Xorg
        - xorg-x11-server-Xwayland
        - sway
        - swayidle
        - swaylock
        - uwsm
        - xdg-desktop-portal-wlr
        - tofi # Your core app launcher
        - mako # Notification daemon
        - i3status-rust # Your status bar
        - wlr-randr
        - wl-clipboard
        - wdisplays # or wlr-randr
        - foot # Your primary terminal
        - gnome-keyring # For password/secret management

        # --- Graphics, Media Drivers & Codecs ---
        - xorg-x11-nvidia # Keep if you have an Nvidia GPU
        - qt5-qtwayland
        - qt6-qtwayland
        - pipewire
        - wireplumber
        - ffmpeg
        - gstreamer1
        - gstreamer1-plugin-vaapi
        - gstreamer1-plugin-libav
        - gstreamer1-plugin-mp4
        - gstreamer1-plugin-fmp4
        - gstreamer1-plugin-dav1d
        - gstreamer1-plugin-openh264
        - gstreamer1-plugins-ugly
        - nvidia-sdk-video-codec
        - openh264
        - libvkd3d

        - cuda
#        - cuda-toolkit

        # --- Core System & Services ---
        - fprintd-pam # For fingerprint support
        - tailscale
        - zsh # If this is your default shell
        - starship
        - lm_sensors
        - git
        - gh
        - gitui

        # --- Essential User Applications & Utilities ---
        - satty # Screenshots are a core function
        - grimshot
        - playerctl # For media key control
        - yazi
        - trash-cli
        - exiftool

        # --- Hardware & Device Integration ---
        - usbmuxd # For Apple device support
        - libimobiledevice-utils
        - ifuse
        - android-tools
        - nut # If you use a UPS
        - openrgb-0.9 # For RGB peripheral control
        - libi2c-devel # For openrgb
        - liquidctl
        - libxcrypt-compat
        - gphoto2
        - gphotofs
 #       - opentabletdriver


    remove:
      packages:
        - noopenh264
        - firefox

  - type: dnf
    repos:
      cleanup: true
      copr:
        - gloriouseggroll/nobara-42
    install:
      packages:
        - opentabletdriver

  - type: files
    files:
    - source: finish-setup.service
      destination: /usr/lib/systemd/system/finish-setup.service
 #   - source: finish-setup-user.service
 #     destination: /usr/lib/systemd/user/finish-setup-user.service
    - source: finish-setup.sh
      destination: /etc/finish-setup/finish-setup.sh
    - source: finish-setup-user.sh
      destination: /etc/finish-setup/finish-setup-user.sh
    - source: home
      destination: /etc/finish-setup/home

#  - type: script
#    scripts:
#      - install-ly.sh

  - type: systemd

    system:
      enabled:
        - finish-setup.service
        - tailscaled.service
#    user:
#      enabled:
#        - finish-setup-user.service

  - type: default-flatpaks
    user:
      install:
        - org.mozilla.firefox
        - org.chromium.Chromium
        - io.mpv.Mpv

  - type: fonts
    fonts:
      nerd-fonts:
        - Hack
        - SourceCodePro
        - JetBrainsMono
        - CodeNewRoman
        - NerdFontsSymbolsOnly

  - type: signing



#- https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-42.noarch.rpm
#- https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-42.noarch.rpm
#- https://negativo17.org/repos/fedora-nvidia.repo
#- https://negativo17.org/repos/fedora-multimedia.repo
#- https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-42/atim-starship-fedora-42.repo
