[theme.overrides]
idle_bg = "#000000"
idle_fg = "#FFFFFF"
separator = "   |   "

[[block]]
block = "memory"
format = "RAM ($mem_used/$mem_total )"

[[block]]
block = "cpu"
interval = 1
format = "CPU $utilization"

[[block]]
block = "temperature"
interval = 1
format = "Temp $average avg"
chip = "*-isa-*"
#inputs = ["CPUTIN", "SYSTIN"]

#[[block]]
#block = "nvidia_gpu"
#gpu_id = 1
#interval = 1
#format = "RTX 4090 $utilization $temperature $power $memory"

[[block]]
block = "sound"
format = "Vol {$volume|Mute}"

#[[block]]
#block = "music"
#format = "$combo.str(max_w:35,rot_interval:0.1)"

[[block]]
block = "net"
device = "wlo1"
interval = 1
format = "$ssid ($signal_strength/$frequency): $speed_down.eng(w:4)/$speed_up.eng(w:4)"

[[block]]
block = "net"
device = "enp3s0"
interval = 1
format = "Wired ($ip): $speed_down.eng(w:4)/$speed_up.eng(w:4)"

[[block]]
block = "speedtest"
interval = 1800 # 30 min
format = "Speed $speed_down.eng(w:4)/$speed_up.eng(w:4)"

[[block]]
block = "time"
interval = 1
format = "$timestamp.datetime(f:'%a %m/%d %I:%M %p')"
